added facet preview and initial product photos preview
aexol-studio/vendure-nextjs-storefront pull request #2
Opened 2023-12-11 23:49 UTC by ghosttly

2023-12-12 12:28 UTC, aexol requested changes
małe zmiany

2023-12-12 12:28 UTC, aexol commented on src/components/atoms/Facet.tsx
> +    padding: 0.4rem 1.8rem;
tutaj wolałbym do 0.25 zaokrąglać

2023-12-12 12:28 UTC, aexol commented on src/components/atoms/Facet.tsx
> +    border-radius: 2rem;
border-radius z thema trza brać

2023-12-12 12:33 UTC, ghosttly commented on src/components/atoms/Facet.tsx
> +    border-radius: 2rem;
oki

2023-12-12 12:33 UTC, ghosttly commented on src/components/atoms/Facet.tsx
> +    padding: 0.4rem 1.8rem;
oki

2023-12-13 10:29 UTC, aexol requested changes

2023-12-13 10:29 UTC, aexol commented on src/components/atoms/ImageSwitcherArrow.tsx
> +    disabled: boolean;
disabled jak jest boolean to musi być optional

2023-12-13 10:29 UTC, aexol commented on src/components/atoms/ProductImage.tsx
> +        rounded &&
nie rób rounded bo albo masz rounded cały projekt albo border-radius globalny na 0 to niepotrzebny props

2023-12-13 10:29 UTC, aexol commented on src/components/organisms/ProductPhotosPreview.tsx
> +    const isArrowDisabled = useCallback(
takie rzeczy robi się na useMemo a nie na useCallback

2023-12-13 10:29 UTC, aexol commented on src/util/translateFacetsNames.ts
> + * @param language - choosen language
Nie róbmy takich docsów kodu - takie docsy daje typescript. lepszy jest komentarz całej funkcji co ona robi

2023-12-14 08:23 UTC, merged